apiVersion: v1
kind: Secret
metadata:
  name: db-connect-secret
  namespace: nodejs-backend
type: Opaque
data:
  PG_HOST: d2FiYW5rLXBvc3RncmVzcWwtZGV2LnBvc3RncmVzLmRhdGFiYXNlLmF6dXJlLmNvbQ==
  PG_PORT: NTQzMg==
  PG_USER: cG9zdGdyZXM=
  PG_DATABASE: d2FiYW5rMi1ub2RlanM=
  PG_PASSWORD: ZzZLMHFkMFJTeDV4dXdLMkllVU4=