apiVersion: apps/v1
kind: Deployment
metadata:
  name: wabank-nodejs-deploy
  namespace: nodejs-backend
  labels:
    app: wabank-nodejs-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wabank-nodejs-deploy
  template:
    metadata:
      labels:
        app: wabank-nodejs-deploy
    spec:
      containers:
      - name: wabank-nodejs-deploy
        image: wabankcontainerregistry.azurecr.io/nodejs-deposit:latest
      imagePullSecrets:
      - name: acr-secret
        env:
          - name: PG_HOST
            valueFrom:
              secretKeyRef:
                name: db-connect-secret
                key: PG_HOST
          - name: PG_PORT
            valueFrom:
              secretKeyRef:
                name: db-connect-secret
                key: PG_PORT
          - name: PG_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-connect-secret
                key: PG_USERNAME
          - name: PG_NAME
            valueFrom:
              secretKeyRef:
                name: db-connect-secret
                key: PG_NAME
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-connect-secret
                key: PG_PASSWORD