apiVersion: apps/v1
kind: Deployment
metadata:
  name: wabank-nodejs-deploy
  namespace: nodejs-backend
  labels:
    app: wabank-nodejs-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wabank-nodejs-deploy
  template:
    metadata:
      labels:
        app: wabank-nodejs-deploy
    spec:
      containers:
      - name: wabank-nodejs-deploy
        image: wabankcontainerregistry.azurecr.io/nodejs-deposit:latest
      imagePullSecrets:
      - name: acr-secret
        env:
        - name: PGHOST
          valueFrom:
            secretKeyRef:
              name: db-connect-secret
              key: PGHOST
        - name: PGPORT
          valueFrom:
            secretKeyRef:
              name: db-connect-secret
              key: PGPORT
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: db-connect-secret
              key: PGUSER
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              name: db-connect-secret
              key: PGDATABASE
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: db-connect-secret
              key: PGPASSWORD