apiVersion: v1
kind: Service
metadata:
  labels:
    app: wabank-nodejs-deploy
  name: deposits-svc
  namespace: nodejs-dev
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: wabank-nodejs-deploy
  type: LoadBalancer